<?php
$aluno = 'João Carlos de Souza Espinato';

$convidadosPadrao = [
    ['nome'=>'Paula','tipo'=>'adulto'],
    ['nome'=>'Lucas (filho de Paula)','tipo'=>'crianca'],
    ['nome'=>'Marina (filha de Paula)','tipo'=>'crianca'],
    ['nome'=>'Carlos','tipo'=>'adulto'],
    ['nome'=>'Ana','tipo'=>'adulto'],
    ['nome'=>'Bruno','tipo'=>'adulto'],
    ['nome'=>'Camila','tipo'=>'adulto'],
    ['nome'=>'Daniel','tipo'=>'adulto'],
    ['nome'=>'Eduarda','tipo'=>'adulto'],
    ['nome'=>'Felipe','tipo'=>'adulto'],
    ['nome'=>'Gabriela','tipo'=>'adulto'],
    ['nome'=>'Henrique','tipo'=>'adulto'],
    ['nome'=>'Isabela','tipo'=>'adulto'],
    ['nome'=>'João','tipo'=>'adulto'],
    ['nome'=>'Karina','tipo'=>'adulto'],
    ['nome'=>'Leonardo','tipo'=>'adulto'],
    ['nome'=>'Mariana','tipo'=>'adulto'],
    ['nome'=>'Nicolas','tipo'=>'adulto'],
    ['nome'=>'Olivia','tipo'=>'adulto'],
    ['nome'=>'Pedro','tipo'=>'adulto'],
    ['nome'=>'Rafaela','tipo'=>'adulto'],
    ['nome'=>'Samuel','tipo'=>'adulto'],
    ['nome'=>'Tatiane','tipo'=>'adulto'],
    ['nome'=>'Vinícius','tipo'=>'adulto'],
    ['nome'=>'Yasmin','tipo'=>'adulto'],
    ['nome'=>'André','tipo'=>'adulto'],
    ['nome'=>'Beatriz','tipo'=>'adulto'],
    ['nome'=>'Caio','tipo'=>'adulto'],
    ['nome'=>'Davi','tipo'=>'crianca'],
    ['nome'=>'Laura','tipo'=>'crianca'],
];

$produtosPadrao = [
    ['id'=>1,'nome'=>'Picanha','grupo'=>'Sólidos','unidade'=>'kg','adulto'=>0.12,'crianca'=>0.07,'icone'=>'🥩'],
    ['id'=>2,'nome'=>'Linguiça','grupo'=>'Sólidos','unidade'=>'kg','adulto'=>0.10,'crianca'=>0.06,'icone'=>'🌭'],
    ['id'=>3,'nome'=>'Frango','grupo'=>'Sólidos','unidade'=>'kg','adulto'=>0.10,'crianca'=>0.06,'icone'=>'🍗'],
    ['id'=>4,'nome'=>'Pão de alho','grupo'=>'Sólidos','unidade'=>'unid.','adulto'=>1.00,'crianca'=>0.50,'icone'=>'🥖'],
    ['id'=>5,'nome'=>'Arroz','grupo'=>'Sólidos','unidade'=>'kg','adulto'=>0.08,'crianca'=>0.05,'icone'=>'🍚'],
    ['id'=>6,'nome'=>'Farofa','grupo'=>'Sólidos','unidade'=>'kg','adulto'=>0.05,'crianca'=>0.03,'icone'=>'🥣'],
    ['id'=>7,'nome'=>'Vinagrete','grupo'=>'Sólidos','unidade'=>'kg','adulto'=>0.06,'crianca'=>0.04,'icone'=>'🥗'],
    ['id'=>8,'nome'=>'Queijo coalho','grupo'=>'Sólidos','unidade'=>'kg','adulto'=>0.06,'crianca'=>0.04,'icone'=>'🧀'],
    ['id'=>9,'nome'=>'Refrigerante','grupo'=>'Líquidos','unidade'=>'L','adulto'=>0.35,'crianca'=>0.45,'icone'=>'🥤'],
    ['id'=>10,'nome'=>'Suco','grupo'=>'Líquidos','unidade'=>'L','adulto'=>0.20,'crianca'=>0.35,'icone'=>'🧃'],
    ['id'=>11,'nome'=>'Água','grupo'=>'Líquidos','unidade'=>'L','adulto'=>0.40,'crianca'=>0.45,'icone'=>'💧'],
    ['id'=>12,'nome'=>'Cerveja','grupo'=>'Líquidos','unidade'=>'latas 350 ml','adulto'=>4.00,'crianca'=>0.00,'icone'=>'🍺'],
    ['id'=>13,'nome'=>'Gelo','grupo'=>'Apoio','unidade'=>'kg','adulto'=>0.50,'crianca'=>0.50,'icone'=>'🧊'],
    ['id'=>14,'nome'=>'Carvão','grupo'=>'Apoio','unidade'=>'kg','adulto'=>0.15,'crianca'=>0.15,'icone'=>'🔥'],
    ['id'=>15,'nome'=>'Descartáveis','grupo'=>'Apoio','unidade'=>'kits','adulto'=>1.00,'crianca'=>1.00,'icone'=>'🍽️'],
];
